jobs:
  track_digital:
    docker:
      - image: "circleci/python:3.6.1"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              # pylint src tests -- Major overhaul needed to not fail linting, not including linting in tests for now
              # mypy src tests
              pytest --cov=track tests
          name: "Running tests"
    working_directory: ~/repo/track_digital
  tracker:
    docker:
      - image: "circleci/python:3.6.1"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              pylint data tests 
              # mypy src tests
              pytest --cov=data tests
          name: "Running tests"
    working_directory: ~/repo/tracker
  tracker_integration:
    docker:
      - image: "circleci/python:3.6.1"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              mkdir -p domain-scan && wget -q -O - https://api.github.com/repos/cds-snc/domain-scan/tarball | tar xz --strip-components=1 -C domain-scan
              pip install -r domain-scan/requirements.txt
              pip install -r domain-scan/requirements-scanners.txt
          name: "Installing dependencies"
      - run:
          command: |
              sudo apt-get install -y apt-transport-https
              sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
              echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
              sudo apt-get update
              sudo apt-get install -y mongodb-org-tools=3.6.2
          name: "Installing dependencies"
      - run:
          command: |
              mkdir csv
              cat > ./csv/owners.csv  << EOF
              domain,filler,organization_en,organization_fr
              canada.ca,,Shared Services Canada,Services partagés Canada
              digital.canada.ca,,Treasury Board Secretariat,Secrétariat du Conseil du Trésor
              numerique.canada.ca,,Treasury Board Secretariat,Secrétariat du Conseil du Trésor
              EOF
              cat > ./csv/domains.csv  << EOF
              domain
              canada.ca
              digital.canada.ca
              numerique.canada.ca
              open.canada.ca
              ouvert.canada.ca
              cra-arc.gc.ca
              EOF
              cat > ./csv/ciphers.csv << EOF
              cipher
              TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
              TLS_ECDHE_ECDSA_WITH_AES_128_CCM
              TLS_ECDHE_ECDSA_WITH_AES_256_CCM
              TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
              TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
              TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
              TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
              TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
              TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
              TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
              TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
              TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
              TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
              TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
              TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
              TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
              TLS_DHE_RSA_WITH_AES_128_CCM
              TLS_DHE_RSA_WITH_AES_256_CCM
              TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
              TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
              TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
              TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
              TLS_DHE_DSS_WITH_AES_128_CBC_SHA
              TLS_DHE_RSA_WITH_AES_128_CBC_SHA
              TLS_DHE_DSS_WITH_AES_256_CBC_SHA
              TLS_DHE_RSA_WITH_AES_256_CBC_SHA
              TLS_RSA_WITH_AES_128_GCM_SHA256
              TLS_RSA_WITH_AES_256_GCM_SHA384
              TLS_RSA_WITH_AES_128_CCM
              TLS_RSA_WITH_AES_256_CCM
              TLS_RSA_WITH_AES_128_CBC_SHA256
              TLS_RSA_WITH_AES_256_CBC_SHA256
              TLS_RSA_WITH_AES_128_CBC_SHA
              TLS_RSA_WITH_AES_256_CBC_SHA
              EOF
              . .env/bin/activate
              tracker insert ./csv/owners.csv ./csv/domains.csv ./csv/ciphers.csv
          name: "Populating domains"
      - run:
          command: |
              . .env/bin/activate
              tracker preprocess
              export DOMAIN_SCAN_PATH=$(pwd)/domain-scan/scan
              export DOMAIN_GATHER_PATH=$(pwd)/domain-scan/gather
              tracker run
          name: "Creating scan results"
      - run: "mkdir -p workspace"
      - run:
          command: "mongoexport --db track --collection meta --out workspace/mongo_dump"
          name: "Exporting database"
      - persist_to_workspace:
          paths:
            - mongo_dump
          root: workspace
    working_directory: ~/repo/tracker
  track_digital_integration:
    docker:
      - image: "circleci/python:3.6.1"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
          name: "Installing dependencies"
      - run:
          command: |
              sudo apt-get install apt-transport-https
              sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
              echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
              sudo apt-get update
              sudo apt-get install -y mongodb-org-tools=3.6.2
          name: "Installing packages"
      - run:
          command: "mongoimport --db track --collection meta --file /tmp/workspace/mongo_dump"
          name: "Importing database"
      - run:
          command: |
              echo "Run integration tests"
    working_directory: ~/repo/track_digital
  deploy_site:
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker
      - run:
          command: |
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              docker build  -t "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" -t "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest" .
              docker push "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
              docker push "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest"
          name: "Build and Deploy Website Docker Image"
    working_directory: ~/repo/track_digital
workflows:
  version: 2
  tracker:
    jobs:
      - track_digital 
      - tracker
      - deploy_site:
          filters:
            branches:
              only:
                - master
          requires:
            - track_digital
            - tracker
